version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

## 设置mysql，redis持久化保存
#volumes:
#  redis:

services:
  # kimi
#  kimi-free-api:
  #    container_name: kimi-free-api
  #    image: vinlic/kimi-free-api:latest
  #    restart: always
  #    ports:
  #      - "8000:8000"
  #    environment:
  #      - TZ=Asia/Shanghai
  #    networks:
  #      network:
  #        # 在network网络下的容器内部的Ipv4地址
  #        ipv4_address: 177.7.0.15
  #
  #
  #  qwen-free-api:
  #    container_name: qwen-free-api
  #    image: vinlic/qwen-free-api:latest
  #    restart: always
  #    ports:
  #      - "9000:8000"
  #    environment:
  #      - TZ=Asia/Shanghai
  #    networks:
  #      network:
  #        # 在network网络下的容器内部的Ipv4地址
  #        ipv4_address: 177.7.0.16

  # web服务
  web:
    build:
      context: ./web
      # 指定dockerfile启动容器
      dockerfile: ./Dockerfile
    # 自定义容器名
    container_name: gva-web
    # 容器启动失败是否重启
    restart: always
    # 映射端口
    ports:
      - '80:80'
    # web服务依赖于server服务
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    environment:
      - TZ=Asia/Shanghai
    networks:
      network:
        # 在network网络下的容器内部的Ipv4地址
        ipv4_address: 177.7.0.11

  # server服务
  server:
    build:
      context: ./server
      # 指定dockerfile启动容器
      dockerfile: ./Dockerfile
    # 自定义容器名
    container_name: gva-server
    # 容器启动失败是否重启
    restart: always
    # 映射端口
    ports:
      - '8888:8888'
    # server服务依赖于mysql服务于redis服务
    environment:
      - TZ=Asia/Shanghai
    networks:
      network:
        # 在network网络下的容器内部的Ipv4地址
        ipv4_address: 177.7.0.12

  #  mysql:
  #    # 指定mysql镜像版本
  #    # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
  #    image: mysql:8.0.21
  #    # 自定义容器名
  #    container_name: gva-mysql
  #    # 设置utf8字符集
  #    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #    # 容器启动失败是否重启
  #    restart: always
  #    # 映射端口
  #    ports:
  #      - "13306:3306"  # host物理直接映射端口为13306
  #    # 映射数据卷到数据库
  #    volumes:
  #      - mysql:/var/lib/mysql
  #    networks:
  #      network:
  #        # 在network网络下的容器内部的Ipv4地址
  #        ipv4_address: 177.7.0.13

  # redis服务
#  redis:
#    # 指定redis镜像版本
#    image: redis:6.0.6
#    # 自定义容器名
#    container_name: gva-redis # 容器名
#    # 容器启动失败是否重启
#    restart: always
#    # 映射端口
#    ports:
#      - '6379:6379'
#    networks:
#      network:
#        # 在network网络下的容器内部的Ipv4地址
#        ipv4_address: 177.7.0.14
