version: "3"

# 设置mysql，redis持久化保存
volumes:
  redis:

services:
  web:
    image: node:16
    container_name: gva-web
    hostname: gva-web           #可以通过容器名访问
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    working_dir: /web       # 如果docker 设置了workdir 则此处不需要设置
    #若网络不太好，请自行换源，如下
    #command: bash -c "yarn config set registry https://registry.npm.taobao.org --global && yarn install && yarn serve"
    command: bash -c "yarn install && yarn serve"
    volumes:
      - ../../web:/web

  server:
    image: golang:1.18
    container_name: gva-server
    hostname: gva-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - redis
    volumes:
      - ../../server:/server
    working_dir: /server    # 如果docker 设置了workdir 则此处不需要设置 
    command: bash -c "go env -w GOPROXY=https://goproxy.cn,direct && go mod tidy && go run main.go"
    links:
      - redis



  redis:
    image: redis:6.0.6
    container_name: gva-redis # 容器名
    hostname: gva-redis
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - redis:/data
